# spring.datasource.url=jdbc:sqlserver://localhost:1435;databaseName=DOCSCRIPT;integratedSecurity=false;authentication=SqlPassword
# spring.datasource.username=sa
# spring.datasource.password=${DB_PASSWORD}
# spring.jpa.show-sql=true
# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


# logging.level.com.zaxxer.hikari=DEBUG
# logging.level.org.springframework.jdbc.datasource=DEBUG
# logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
# logging.level.org.hibernate.engine.jdbc.env.internal=DEBUG
# logging.level.org.springframework.core.env=DEBUG


spring.datasource.url=jdbc:sqlserver://localhost:1435;databaseName=DOCSCRIPT;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Propriedades do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

bezkoder.app.jwtSecret=${JWT_SECRET}
bezkoder.app.jwtExpirationMs= 86400000