# Configurações do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/discipulus_v1
spring.datasource.username=postgres
spring.datasource.password=iury1973
# Configurações do Hibernate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
server.address=0.0.0.0

com.unirios.jwtSecret=bezKoderSecretKey
com.unirios.jwtExpirationMs=86400000

# ================================
# CONFIGURAÇÕES DO MINIO (STORAGE)
# ================================
minio.endpoint=http://localhost:9000
minio.access.key=minioadmin
minio.secret.key=minioadmin
minio.bucket.name=discipulus-bucket
minio.region=us-east-1