# Configurações do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/discipulus_v1
spring.datasource.username=postgres
spring.datasource.password=iury1973
# Configurações do Hibernate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

com.unirios.jwtSecret=bezKoderSecretKey
com.unirios.jwtExpirationMs=86400000